Your FIFA project goes here:

In [14]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv("./file_for_project/fifa21_training.csv")

In [16]:
pd.set_option('display.max_columns', None)
data.head(2)

,Unnamed: 0,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,1954,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,1,"Jul 1, 2015",NaN,€525K,€4K,€801K,2015 ~ 2020,258,54,47,43,70,44.0,286,61,44.0,55,63,63,346,64,73,61.0,66,82.0,306,62,73.0,71,55,45,290,54,52.0,62.0,68.0,54,54.0,148,49,56,43.0,48,7,12,14,9,6,1682,357,4 ★,2★,High,Medium,1 ★,69,51,63,63,51,60,3,58+1,58+1,58+1,61+0,62+0,62+0,62+0,61+0,63+1,63+1,63+1,63+1,63+1,63+1,63+1,63+1,59+1,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,2225,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,0,"Jan 16, 2015","Dec 31, 2020",€8.5M,€23K,€0,"Dec 31, 2020 On Loan",365,66,79,76,68,76.0,375,83,78.0,72,63,79,404,83,83,88.0,75,75.0,372,74,81.0,75,74,68,313,54,33.0,78.0,72.0,76,70.0,77,35,20,22.0,55,11,7,14,7,16,1961,412,3 ★,4★,High,Low,2 ★,83,75,68,82,33,71,44,77+0,77+0,77+0,77+0,77+0,77+0,77+0,77+0,76+1,76+1,76+1,76+1,68+2,68+2,68+2,76+1,57+2,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77

In [35]:
data.shape

(13700, 102)

In [5]:
import pickle

a = {'hello': 'world'}

In [6]:
with open('filename.pickle', 'wb') as handle:
    pickle.dump(a, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [7]:
with open('filename.pickle', 'rb') as handle:
    b = pickle.load(handle)

In [8]:
print(a == b)

True

In [9]:
b

{'hello': 'world'}

In [42]:
data['Nationality'].unique()

array(['Switzerland', 'China PR', 'Italy', 'Wales', 'France',
       'Bosnia Herzegovina', 'Argentina', 'Paraguay', 'Uruguay',
       'United States', 'Mexico', 'Chile', 'Germany', 'Nigeria', 'Spain',
       'Norway', 'Russia', 'England', 'Republic of Ireland', 'Cape Verde',
       'Bulgaria', 'Zambia', 'Honduras', 'Albania', 'Finland', 'Ghana',
       'Japan', 'Cameroon', 'Peru', 'Austria', 'Congo', 'Colombia',
       'Belgium', 'Brazil', 'Korea Republic', 'Hungary', 'Morocco',
       'Kosovo', 'Netherlands', 'Sweden', 'Scotland', 'Denmark',
       'Northern Ireland', 'Turkey', 'Poland', 'Ivory Coast', 'Bolivia',
       'Ukraine', 'Ecuador', 'Malaysia', 'DR Congo', 'Mali', 'Romania',
       'Slovenia', 'United Arab Emirates', 'Australia', 'Venezuela',
       'Montenegro', 'Slovakia', 'Curacao', 'Portugal', 'Senegal',
       'Lebanon', 'Serbia', 'Iran', 'Zimbabwe', 'Iceland', 'Burkina Faso',
       'Czech Republic', 'Iraq', 'Costa Rica', 'Canada', 'Libya', 'Benin',
       'Korea DPR', 'Algeria', 'Angola', 'Saudi Arabia', 'Togo',
       'South Sudan', 'Croatia', 'Comoros', 'Burundi', 'Vietnam',
       'New Zealand', 'Greece', 'Jamaica', 'India', 'Lithuania', 'Aruba',
       'Papua New Guinea', 'South Africa', 'Liberia', 'Haiti', 'Guyana',
       'Guinea', 'Luxembourg', 'Egypt', 'Afghanistan', 'Tunisia',
       'Uzbekistan', 'Equatorial Guinea', 'Georgia', 'Chinese Taipei',
       'Dominican Republic', 'Indonesia', 'Moldova', 'Gambia', 'Cyprus',
       'Cuba', 'Israel', 'Armenia', 'North Macedonia', 'Gabon', 'Kenya',
       'Trinidad &amp; Tobago', 'Philippines', 'Azerbaijan', 'Latvia',
       'Sudan', 'Mozambique', 'Panama', 'Antigua &amp; Barbuda',
       'Mauritania', 'Liechtenstein', 'Madagascar', 'Guinea Bissau',
       'Qatar', 'Uganda', 'Thailand', 'Faroe Islands',
       'Saint Kitts and Nevis', 'Estonia', 'Grenada', 'Belarus', 'Guam',
       'Sierra Leone', 'New Caledonia', 'Namibia', 'Jordan',
       'Central African Republic', 'Syria', 'Macau', 'Kazakhstan',
       'Malawi', 'Rwanda', 'Hong Kong', 'Singapore', 'Chad', 'Palestine',
       'Barbados', 'Belize', 'Gibraltar', 'El Salvador', 'Malta',
       'São Tomé &amp; Príncipe', 'Puerto Rico', 'Niger', 'Tanzania',
       'Eritrea'], dtype=object)

In [44]:
import pycountry_convert

In [47]:
pycountry_convert.convert_countries.country_name_to_country_alpha2('Malawi')

'MW'

In [48]:
pycountry_convert.country_alpha2_to_continent_code('MW')

'AF'

In [52]:
data['Height'].str.contains("\"").sum()

13700

In [55]:
data['Height'][0].split("'")[0]

'5'

In [57]:
data['Height'][0].split("'")[1][:-1]

'9'

In [60]:
float(data['Height'][0].split("'")[0])*12 + float(data['Height'][0].split("'")[1][:-1])

69.0

In [17]:
data

,Unnamed: 0,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,1954,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,2225,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,1959,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,9815,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,10074,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13695,11284,239074,S. Aw,21,Senegal,Gil Vicente FC,LB,LB,Gil Vicente FC 2020 ~ 2023,"5'8""",...,52+2,52+2,58+2,58+2,54+2,54+2,54+2,58+2,15+2,60
13696,11964,241223,S. Mogi,21,Japan,Cerezo Osaka,GK,GK,Cerezo Osaka 2017 ~ 2021,"6'5""",...,23+2,23+2,20+2,20+2,22+2,22+2,22+2,20+2,58+2,59
13697,5390,210930,Carles Gil,27,Spain,New England Revolution,RM,RM CAM CM,New England Revolution 2019 ~ 2024,"5'7""",...,60+2,60+2,62+2,57+2,47+2,47+2,47+2,57+2,18+2,76
13698,860,162993,J. Perch,34,England,Mansfield Town,CDM,CDM RB CM,Mansfield Town 2020 ~ 2021,"5'11""",...,62+1,62+1,60+2,60+2,63+0,63+0,63+0,60+2,14+2,63
13699,15795,254882,A. Oeynhausen,18,Germany,SC Paderborn 07,CAM,CM,SC Paderborn 07 2020 ~ 2022,"5'10""",...,55+2,55+2,55+2,54+2,51+2,51+2,51+2,54+2,16+2,60

In [18]:
data=data.drop(['Unnamed: 0','ID','Age','Nationality','Club','Height','Weight','foot','Growth','Team & Contract','Joined','Loan Date End','Value','Wage','Release Clause','Contract'],axis=1)

In [21]:
print(data.isna().sum())

Name           0
BP             0
Position     343
Attacking      0
Crossing       0
            ...
CB             0
RCB            0
RB             0
GK             0
OVA            0
Length: 86, dtype: int64

In [27]:
data=data[['PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY']]

       PAC  SHO  PAS  DRI  DEF  PHY
0       69   51   63   63   51   60
1       83   75   68   82   33   71
2       80   77   78   86   27   56
3       57   44   54   57   57   60
4       66   44   60   64   60   66
...    ...  ...  ...  ...  ...  ...
13695   76   28   46   55   53   57
13696   60   55   57   62   30   54
13697   65   69   78   77   39   60
13698   53   47   58   58   61   69
13699   64   54   62   62   50   47

[13700 rows x 6 columns]